In [7]:
import mlearn
import torch
import mlearn.functional as F
from mlearn.layers import Dense, Conv2d
import numpy as np

In [8]:
a = np.random.randn(3,4)

In [12]:
print(a)

[[ 0.827235    0.36828696  0.65171885  1.65491882]
 [ 2.17868364 -0.47446996  1.02801935  0.14106531]
 [-0.95886884 -0.74322281 -0.0788397   1.14600784]]


In [2]:
class Net(mlearn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = Conv2d(3,8,5,5)
        self.conv2 = Conv2d(8,8,5,5)
        self.dense = Dense(20,5)
        
        
    def forward(self, inputs):
        return conv1(inputs)
net = Net()

In [8]:
net._modules

OrderedDict([('conv1', 二维卷积Object -> ( 3, 8, kernel_size=(5, 5), stride=5 ) ),
             ('conv2', 二维卷积Object -> ( 8, 8, kernel_size=(5, 5), stride=5 ) ),
             ('dense', 全连接层 -> ( Batch Size, 20) => (Batch Size, 5 ))])

In [9]:
net.__dict__

{'_modules': OrderedDict([('conv1',
               二维卷积Object -> ( 3, 8, kernel_size=(5, 5), stride=5 ) ),
              ('conv2', 二维卷积Object -> ( 8, 8, kernel_size=(5, 5), stride=5 ) ),
              ('dense', 全连接层 -> ( Batch Size, 20) => (Batch Size, 5 ))]),
 '_parameters': OrderedDict()}

In [10]:
net.__dict__['_modules']['conv1']

二维卷积Object -> ( 3, 8, kernel_size=(5, 5), stride=5 ) 

In [12]:
net.__dict__['_modules']['dense']._parameters

OrderedDict([('weights', 可訓練的參數
              Tensor([[-0.2891,  1.0286,  0.3472, -0.0188,  0.4378],
                      [-0.1112, -0.1764, -0.0156, -0.5593, -0.5181],
                      [ 0.2446,  0.5748, -0.5268, -0.1835,  0.3648],
                      [ 0.3279,  0.5587,  0.3092, -0.7850, -0.1135],
                      [-0.0363,  0.1224, -0.5291, -0.2516,  0.2991],
                      [ 0.0195, -1.0720, -0.0091,  0.4636, -0.6655],
                      [ 0.2097, -0.5552,  0.2976, -0.8054,  0.0072],
                      [ 0.0826, -0.4075,  0.0093,  0.1670,  0.2445],
                      [-0.1658, -0.1218,  0.3129, -0.1572, -0.0271],
                      [-0.0338, -0.0160,  0.3908, -0.1960,  0.1757],
                      [-0.0902, -0.2091, -0.2020,  0.4809, -0.1964],
                      [-0.1758, -0.4600, -0.4503, -0.3117, -0.2646],
                      [ 0.7576, -0.7371,  0.9362, -0.3658, -0.4534],
                      [ 0.1287,  0.8042, -1.0431,  0.6031, -0.4506],
  